### ISSUE TITLE
script broken, unpacking 7z problem ?

### ISSUE THREAD

**Issue by plissken1138** [Crozzers/ffmpeg-installer#3] opened 2024-03-18 19:34 UTC
The script was working until recently when it stopped unpacking 7z... I'm not sure if something is changed in how patool and pyunpack work or it's a 7z package problem. pyunpack and patool are installed. Here's the whole cmd content:

```
Making install dir 'C:\\ffmpeg'
Downloading 'https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z' to 'C:\\ffmpeg\\ffmpeg-git-full.7z'
Progress: 11.34MB / 50.61MB
Progress: 50.61MB / 50.61MB
Unzipping 'C:\\ffmpeg\\ffmpeg-git-full.7z' to 'C:\\ffmpeg\\ffmpeg-git-full'
Traceback (most recent call last):
  File "d:\ffmpeg-installer-main\update_ffmpeg.py", line 229, in <module>
    decompress(dirs.download_dest, dirs.unzip_dest)
  File "d:\ffmpeg-installer-main\update_ffmpeg.py", line 149, in decompress
    pyunpack.Archive(path).extractall(destination)
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyunpack\__init__.py", line 113, in extractall
    self.extractall_patool(directory, patool_path)
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyunpack\__init__.py", line 74, in extractall_patool
    raise PatoolError("patool can not unpack\n" + str(p.stderr))
pyunpack.PatoolError: patool can not unpack
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Scripts\patool", line 25, in <module>
    from patoolib.util import log_error, log_internal_error, PatoolError
ImportError: cannot import name 'log_error' from 'patoolib.util' (C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\patoolib\util.py)
Press any key to continue . . .
```

Additional question: could the script fetch the releases from https://github.com/GyanD/codexffmpeg instead of gyan.dev ? Github releases include Zip packages for all versions as opposed to the site. There is no problem with unpacking Zip when using the sript.

**Comment by Crozzers** [comment] 2024-03-20 22:55
I was able to reproduce this once, but installed some updates and haven't managed to reproduce it since.
Looks like this specific import issue was probably fixed after patool 1.13. 2.2.0 is now out so I'd recommend upgrading.

I ran into another issue after upgrading which is that patool changed how it bundles its entry point script, which trips up `pyunpack`. They have a fix but haven't deployed it yet (see [issue](https://github.com/ponty/pyunpack/issues/21)).

I'll try to see if we can bypass `pyunpack` and use the updated `patool` directly.

> Additional question: could the script fetch the releases from https://github.com/GyanD/codexffmpeg instead of gyan.dev ?

Only thing the releases don't have are git builds, but I suppose I could try to mix and match them

**Comment by plissken1138** [comment] 2024-03-21 02:28
I already had patool 2.2.0 with python 3.12 installed but it seems it wasn't in PATH but older versions were (there were python 3.10 and 3.11 installed also)... So I did a bit of a cleanup and uninstalled all older versions and re-installed python 3.12 and cleaned all older versions from PATH. Running pip install -r requirements.txt confirmed that patool 2.2.0 and pyunpack 0.3 are installed.

Now the situation is this:

```
Making install dir 'C:\\ffmpeg'
Downloading 'https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z' to 'C:\\ffmpeg\\ffmpeg-git-full.7z'
Progress: 20.27MB / 50.61MB
Progress: 40.44MB / 50.61MB
Progress: 50.61MB / 50.61MB
Unzipping 'C:\\ffmpeg\\ffmpeg-git-full.7z' to 'C:\\ffmpeg\\ffmpeg-git-full'
Traceback (most recent call last):
  File "d:\ffmpeg-installer-main\update_ffmpeg.py", line 229, in <module>
    decompress(dirs.download_dest, dirs.unzip_dest)
  File "d:\ffmpeg-installer-main\update_ffmpeg.py", line 149, in decompress
    pyunpack.Archive(path).extractall(destination)
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyunpack\__init__.py", line 113, in extractall
    self.extractall_patool(directory, patool_path)
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyunpack\__init__.py", line 58, in extractall_patool
    raise ValueError("patool not found! Please install patool!")
ValueError: patool not found! Please install patool!
Press any key to continue . . .
```

Looks like patool isn't recognised as installed (although it is and is added to PATH). Is this the same issue or something different?

**Comment by Crozzers** [comment] 2024-03-23 10:58
That error has been fixed in pyunpack but not released. I've pushed a commit that removes pyunpack and uses patool directly, so that should solve the issue.

> Additional question: could the script fetch the releases from https://github.com/GyanD/codexffmpeg instead of gyan.dev ?

I've added a commit that should enable this. Some of the build names are slightly different on github (`release-essentials` -> `essentials-build`) and there's no way to get the checksum of the github versions, but you should be able to download the full range of builds now

EDIT: pushed another commit to enforce a consistent naming scheme across all build sources. You should now be able to set `--build release-essentials` and it will automatically pick the gyan.dev/github build based on the desired format

**Comment by plissken1138** [comment] 2024-03-23 16:00
EXCEPTIONAL! Much obliged!

**Closed as completed** 2024-03-25 20:37 UTC
